### ISSUE TITLE
Doesn't work on debian jessie zsh 

### ISSUE THREAD

**Issue by vmakarenko** [changyuheng/fz#1]
i.e. with old versions of debian jessie default zsh  5.0.7:
```
~ fz TAB
fz-completion:3: invalid mode specification
```

**Comment by johannjhang** [comment]
That is a very useful mode specification of zsh. fzf uses it too. So currently there's no backward compatibility plan. But any PR is welcome!

**Comment by johannjhang** [comment]
@vmakarenko I've done some changes and verified with zsh v5.0.2. Could you test it again and share the result?
e20c50bbde29c49d42a23da2b17dd2ba980cff0e

**Comment by vmakarenko** [comment]
Works fine with zsh 5.0.7, i.e. `fz` behavior is equal to `z`

**Comment by johannjhang** [comment]
Thank you! I'm gonna close this issue.
