### ISSUE TITLE
有没有办法支持 z.lua ??

### ISSUE THREAD

**Issue by skywind3000** [changyuheng/fz#17]
z.lua 的匹配效果比 z.sh 高效很多，功能也比它强，如果能得到 fz 的支持就十分不错了。
https://github.com/skywind3000/z.lua

**Comment by skywind3000** [comment]
能不能给你提个 PR 支持 z.lua ？？我大概知道怎么改了。

**Comment by johannjhang** [comment]
Of course!

**Comment by skywind3000** [comment]
https://github.com/changyuheng/fz/pull/19

已经创建了 PR 了

**Comment by johannjhang** [comment]
Thank you for the PR, @skywind3000.
