### ISSUE TITLE
Honor $_Z_CMD or intruduce similar environment variable for fz

### ISSUE THREAD

**Issue by caedn** [changyuheng/fz#2]
I use `export _Z_CMD=j` in my `.zshrc` to change the command name from `z` to `j`. Now I'd love to call `fz` with `j` so my muscle memory does not go to waste. 

Maybe introduce `$_FZ_CMD`?

**Comment by johannjhang** [comment]
This is a pretty good idea. Since I hard coded some logic with the actual name `fz`, it'll not be done with a very quick fix. I'll do this when I have time.

**Comment by johannjhang** [comment]
It's done in this commit f3fe733d9631d1b4ed21c974363e043c9418ce20.
