### ISSUE TITLE
tab completion just hangs the shell

### ISSUE THREAD

**Issue by jubishop** [changyuheng/fz#21]
i have fzf installed and working fine with other tings.
z also works fine on its own.

i installed fz after z like so:

zplugin ice wait lucid
zplugin light rupa/z
zplugin ice wait lucid
zplugin light changyuheng/fz

using zplugin.  but it just hangs on tab complete... :( . any ideas?

**Comment by jubishop** [comment]
please note, zplugin loads in the order defined, but just to ensure fz comes later, i've also tried:

zplugin ice wait'1' lucid
zplugin light changyuheng/fz

**Comment by NICHOLAS85** [comment]
I've had success using the following:
```zsh
FZ_HISTORY_CD_CMD=zshz

zplugin ice wait blockf lucid
zplugin agkozak/zsh-z

zplugin ice wait lucid
zplugin light changyuheng/fz
```

Although this uses a different z from the one you tried using.

**Comment by johannjhang** [comment]
Hi! What's the version of your zsh? What's the output of echo $SHELL?

**Comment by jubishop** [comment]
hey thanks sorry i should've closed this, i figured it out :) i had some other stuff going on that was overriding some behavior of "cd", which was somehow causing problems here.  i got it working now :) 

cheers.

**Comment by jubishop** [comment]
however i have never been able to get zsh-z working.  perhaps if i add that FZ_HISTORY_CD_CMD... anyway thanks!
