### ISSUE TITLE
${=fzf}: bad substitution

### ISSUE THREAD

**Issue by svardew** [changyuheng/fz#26]
https://github.com/changyuheng/fz/blob/2a4c1bc73664bb938bfcc7c99f473d0065f9dbfd/fz.sh#L169-L174

maybe ${fzf} ?

**Comment by johannjhang** [comment]
http://zsh.sourceforge.net/Doc/Release/Expansion.html#g_t_0060_003d_0027-expansion

**Comment by svardew** [comment]
Thank you for check this issue.
I use bash, not familiar with zsh.
Bash don't have word split Parameter Expansion ${=SPEC} syntax.

* ubuntu 14.04.6 (i686)
* GNU bash, version 4.4.19(1)-release (i686-pc-linux-gnu)
* zsh 5.0.2 (i686-pc-linux-gnu)
* fzf 0.22.0 (e2ae1b2)
$ /bin/bash -c 'fzf="fzf-tmux arg1"; echo ${=fzf}'
#=> /bin/bash: ${=fzf}: bad substitution
$ /usr/bin/zsh -c 'fzf="fzf-tmux arg1"; echo ${=fzf}'
#=> fzf-tmux arg1

When fz.sh call __fz_filter(), bash cannot expand ${=fzf} and fail to open fzf window

$ bash --norc
export LANG=C
. ~/.fzf.bash
. ~/.bash_completion/z.sh
. ~/.bash_completion/fz.sh
mv ~/.z{,_bak_bash44}
cd ~/.cargo/bin
cd ~/bin
cd /bin
cd /usr/bin
cd /tmp
z bi<TAB>
#=> ERROR; bash-4.4$ z bibash: ${=fzf}: bad substitution
exit

$ zsh -f
export LANG=C
source ~/.bash_completion/z.sh
source ~/.bash_completion/fz.sh
mv ~/.z{,_bak_zsh501}
cd ~/.cargo/bin
cd ~/bin
cd /bin
cd /usr/bin
cd /tmp
z bi<TAB>
#=> SUCCESS; fzf window appear, select and path completion ok.
exit
